# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

print(A)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [7]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

#print(B)
#print(C)

print(f"Elementwise subtraction B-C:\n{B-C}")
print(f"Elementwise multiplikation B*C:\n{B*C}")
print(f"Matrix product B @ C:\n{B@C}")

Elementwise subtraction B-C:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elementwise multiplikation B*C:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
Matrix product B @ C:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [11]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

print(f"Exponentiated B:\n{np.exp(B)}")
print(f"The minimum value in the whole matrix: {np.min(B)}")
print(f"Minimum value in each row: {np.min(B, 1)}")
print(f"Minimum value in each column: {np.min(B, 0)}")
print(f"Index value for minimum value int he whole matrix: {np.argmin(B)}")
print(f"Index value for minimum value in each row: {np.argmin(B, 1)}")
print(f"Sum for all elements: {np.sum(B)}")
print(f"Mean for each column: {np.mean(B, 0)}")
print(f"Median for each column: {np.median(B, 0)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Exponentiated B:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
The minimum value in the whole matrix: 1
Minimum value in each row: [1 4 7]
Minimum value in each column: [1 2 3]
Index value for minimum value int he whole matrix: 0
Index value for minimum value in each row: [0 0 0]
Sum for all elements: 45
Mean for each column: [4. 5. 6.]
Median for each column: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [12]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [13]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
#I det här fallet innebär det att jag hämtar en hel rad, den på index 1. För att hämta en hel kolumn, A[:, 1]. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [15]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [19]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [ ]:
a = np.arange(30) # Skapar en lista med 30 element, den börjar från 0 och sista blir då 29.
b = a.reshape((2, 3, -1)) # Formar listan till en matris med 2 block med 3 rader och det antalet kolummner som behövs för att rymma alla 30 element.
print(a) 
print()

print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [23]:
# Att den har 3 dimensioner kan ses som att första värdet: 2, anger hur många block/lager matrisen ska ha. Andra värdet styr antalet rader och tredje styr antal kolumner. 
# Det kan till exempel handla om bildhantering där man kan lägga olika färglager på varandra och skapa filter. 

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [24]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [25]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [26]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [61]:
def add_mult_matrices(matrix1, matrix2, operation):
    """
    En funktion som tar in 2 matriser och antingen adderar eller multiplicerar.
    Anropa funktionen så här: (A, B, "add") eller (A, B, "multiply").
    Just nu printar den resultatet direkt i terminalen. En förbättring skulle vara att returnera resultatet istället för att bara printa ut? 
    """
    if isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray):

        if operation == "add":
            if matrix1.shape == matrix2.shape:
                print(f"The result of Matrix addition is:\n {matrix1 + matrix2}")
                #return result(matrix1 + matrix2)
            else:
                print("The matrices dont have the same shape and can not be added together. Please correct and try again!")


        elif operation == "multiply":
            if matrix1.shape[1] == matrix2.shape[0]:
                print(f"The matrix product is:\n {matrix1 @ matrix2}")
                #return result(matrix1 @ matrix2)
            else:
                print("The number of columns in matrix 1 must match the number of rows in matrix 2. Please correct and try again.")

    else:
        print("You have not provided two correct matrices, please try again.")



In [62]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
add_mult_matrices(A, B, "add")

The result of Matrix addition is:
 [[ 8 10 12]
 [14 16 18]]


In [63]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
add_mult_matrices(A, B, "multiply")

The matrix product is:
 [[ 66  72  78]
 [156 171 186]
 [246 270 294]]


In [64]:
# Should print out failure message
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[7, 8, 9], [10, 11, 12]])
add_mult_matrices(A, B, "multiply")

The number of columns in matrix 1 must match the number of rows in matrix 2. Please correct and try again.


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [65]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [66]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [67]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
